# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      
    - name: Setup buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker
      
    - name: Login to DockerHub
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.TREESCALE_USERNAME }}
        password: ${{ secrets.TREESCALE_PASSWORD }}
        registry: repo.treescale.com

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.1
      with:
        tags: diliproshitha/journal-your-trade-api-gateway:latest
        context: .
        registry: repo.treescale.com
        push: true
        username: ${{ secrets.TREESCALE_USERNAME }}
        password: ${{ secrets.TREESCALE_PASSWORD }}
